### ISSUE TITLE
processPrefix renames busybox64.exe, which breaks it

### ISSUE THREAD

**Issue by doctorpangloss** [rancher/wins#110]
1. Try to run `busybox64.exe` using `wins`.
 2. Observe it renames the executable to `rancher-wins-busybox64.exe`.
 3. This breaks `busybox64.exe` with error `rancher-wins-busybox64: applet not found`, because its functionality depends on the name of the command that executes it.

There should probably be a way to execute a file without renaming it.

**Comment by doctorpangloss** [comment]
FYI, removing the renaming code seems to work fine.

There's a lot of mysterious things going on with `wins`, but it's the only game in town.

**Comment by rosskirkpat** [comment]
@doctorpangloss The purpose of renaming the binaries is to distinguish if the binary is being run by wins. 

Being able to configure the renaming at run-time as a configuration flag would be ideal. I am re-opening this issue and will put this on our backlog and review it during our next sprint.

**Comment by doctorpangloss** [comment]
> The purpose of renaming the binaries is to distinguish if the binary is being run by wins.

Once you guys discover Job Objects you won't have to do that anymore. You won't have to deal with a process pool either.

**Comment by brandond** [comment]
I have no idea what Zube is doing in my name here but I didn't do any of that labeling or closing.

**Comment by doctorpangloss** [comment]
Use HostProcess containers instead of wins.
