### ISSUE TITLE
Add support for publishing ports

### ISSUE THREAD

**Issue by aiyengar2** [rancher/wins#13]
Wins currently supports exposing ports on the host via an [`--exposes "{TCP|UDP}:{Port}"`](https://github.com/rancher/wins/blob/7c2d5528151cb63355615e1ee02bd59380c1c1e2/cmd/client/process/run.go#L35-L39) option on a running process.

There should be a similar option available for `--publishes "{TCP|UDP}:{Port}"` that allows a container to publish a port available on the host network as a container port. This would allow privileged containers using wins to avoid exposing a port on the host itself when it only needs to be exposed on a container-level (e.g. inter-Pod communication for Kubernetes vs. inter-Node communication).

**Comment by sowmyav27** [comment]
Will wait for this https://github.com/rancher/rancher/issues/28327 epic to be fixed to test this issue out.

**Comment by thehejik** [comment]
I see the support is already incorporated in the wins-0.1.0 binary. Anyway I'd like to test it. 
@aiyengar2 could you please provide me a simple test with description?

I found some bits related to `--exposes` but not for `--publishes` eg.:
https://github.com/rancher/wins/blob/master/tests/integration/docker/nginx.ps1
https://github.com/rancher/wins#readme

This is help from wins command on node wiht rancher-wins-upgrader deployed:

```
administrator@IP-AC1F0A6D C:\etc\rancher>wins cli proxy --help
NAME:
   rancher-wins cli proxy - Set up a proxy for a port via Rancher Wins (note: only TCP is supported)

USAGE:
   rancher-wins cli proxy [command options] [arguments...]

OPTIONS:
   --publish value  [required] [list-argument] Publish a port or a range of ports, e.g.: TCP:443 TCP:80-81 (note: only TCP is supported)
   --proxy value    [optional] Specifies the name of the proxy listening named pipe (default: "rancher_wins_proxy")


administrator@IP-AC1F0A6D C:\etc\rancher>wins --version
rancher-wins version v0.1.0
```

**Comment by thehejik** [comment]
We realized it was actually tested within v2 monitoring testcases in Monitoring+v2+Windows+Support document. Closing.
