### ISSUE TITLE
Add Helm chart for wins upgrades

### ISSUE THREAD

**Issue by aiyengar2** [rancher/wins#20]
Packages https://github.com/rancher/wins/issues/23 into a Helm chart that supports maintaining 1 or more configuration of wins across Windows hosts in a k8s cluster.

Requirements for Testing:
- Need to be able to specify winsConfigs that should be applied to hosts based on nodeSelectors and tolerations
- Need to be able to upgrade wins binary alone for a set of hosts
- Need to be able to upgrade wins config alone for a set of hosts
- Need to be able to upgrade both wins binary and wins config in one shot
- Need to be able to take an existing Windows cluster and successfully deploy this chart even if the processPath for wins upgrade is not whitelisted (e.g. masquerading)

#### Masquerading

Instead of requiring a user who deploys this chart to have to manually upgrade every single windows host to whitelist the path that will contain the version of wins we plan to update to, users should be able to select one option that automatically masquerades the payload of wins upgrade under another whitelisted path. That way, you can bootstrap the upgrade processPath workflow on an existing cluster as a one time step and then switch to the normal upgrade path.

e.g.
```
masquerade:
  enabled: false  
  as: c:\\etc\wmi-exporter\wmi-exporter.exe 
```

**Comment by thehejik** [comment]
Helm chart from `dev-v2.5` repo successfully deployed and tested within the EPIC testing and https://confluence.suse.com/display/EN/Monitoring+v2+Windows+Support

It's compatible with windows nodes deployed on rancher:2.5.7

Installing binary and config on specific host(s) can be achieved by adding a label to node(s) like `type: upgrademe` and then selecting the node in wins-upgrade `Values YAML` form via `nodeSelector:` key (empty one is present in yaml):
```
nodeSelector:
  type: upgrademe
```
