### ISSUE TITLE
Support upgrading wins via wins up

### ISSUE THREAD

**Issue by aiyengar2** [rancher/wins#23]
Adds support for running `.\wins up[grade]`, which runs a Powershell script within wins that restarts the service with a different wins server binary.

This is an alternative to the current mechanism for upgrades that wins provides wherein it watches for a path and utilizes checksums to see whether the service should be modified / restarted and can also be used as an alternative method to enable wins on a Windows host (e.g. you can just run `.\wins up` instead of `.\wins srv app run --register; Start-Service -Name rancher-wins`).

The primary use case of this feature is to support a new Helm chart that will allow users to maintain wins configs / wins versions across entire clusters using just a Helm chart for configuration. This Helm chart uses wins (cli) to pass wins (upgrade) to wins (server) in order to update wins (server) on the host on demand. More succinctly it runs:
```powershell
# Transfer the generated config to the directory
Transfer-File -Src "c:\scripts\config" -Dst "c:\host\etc\rancher\wins\config"
# Force a restart of wins server, which will naturally use the newly generated config
wins.exe cli prc run --path=$pathToWinsBinary --args="up --wins-args=`'--register --config=$pathToWinsBinaryDir\config`'"
```

**Comment by thehejik** [comment]
Tested within v2 monitoring testcases in Monitoring+v2+Windows+Support document. Closing.
