### ISSUE TITLE
Wins crashing

### ISSUE THREAD

**Issue by gujjdo** [rancher/wins#68]
Hi,

I seem to have an issue with wins crashing about 30minutes after starting it. Usually I start it as a service in windows but since its crashing I started trying to start it from cmd.

This log is from wins v0.1.2-rc2, however the crash occurs in v0.1.1 as well but cmd crashed/disappeared when running that version so I have no logs from v0.1.1.

Additionally I would like to add that setting log-level doesn't work either, I get "flag provided but not defined: -log-level" when trying to run: "wins.exe srv app run --log-level debug"

```
>wins.exe srv app run
WARN[2021-12-03T14:40:16+01:00] cannot upgrade unless the current process is being executed as a Windows service
INFO[2021-12-03T14:40:16+01:00] listening for tcp requests on rancher_wins_proxy destined for: []
INFO[2021-12-03T14:40:16+01:00] Rancher System Agent configuration now found, not starting system agent.
INFO[2021-12-03T14:40:16+01:00] Listening on \\.\pipe\rancher_wins_proxy
INFO[2021-12-03T14:40:16+01:00] Listening on \\.\pipe\rancher_wins
WARN[2021-12-03T14:44:33+01:00] [Process] Found stale process rancher-wins-flanneld(7124), try to recreate a new process
WARN[2021-12-03T14:44:50+01:00] [Process] Found stale process rancher-wins-ngin(360), try to recreate a new process
panic: sync: negative WaitGroup counter

goroutine 752 [running]:
sync.(*WaitGroup).Add(0xc0004007f0, 0xffffffffffffffff)
        c:/go/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(0xc0004007f0)
        c:/go/src/sync/waitgroup.go:99 +0x3b
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004007f0, 0xc00034ce00, 0x28fb0b8, 0xc000055e00, 0xc00028a000)        C:/gopath/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:879 +0xc5
created by google.golang.org/grpc.(*Server).serveStreams.func1
        C:/gopath/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
```

**Comment by phillipsj** [comment]
@gujjdo which version of Windows are you running for your host? Do you have the latest updates installed?

**Comment by gujjdo** [comment]
Hi,

Apparently vmware-tools had a bug (around 2019) which could make programs crash. Sadly the admins of the server I was on had somehow missed to update vmware-tools.

Everything has been running smoothly now since the update of vmware-tools.

Thanks for the help and sorry to disturb you.
